version: "3.7"

services:
  database_loja_jogos:
    image: postgres
    container_name: database_loja_jogos
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_DB=loja_jogos
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: app-loja-jogos
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database_loja_jogos
    depends_on:
      - database_loja_jogos

volumes:
  pgdata:
    driver: local